[package]
name = "numaflow-monitor"
version = "0.1.0"
edition = "2021"


[lints]
workspace = true

[dependencies]
tokio.workspace = true
tokio-util = "0.7.11"
tracing.workspace = true
numaflow-models.workspace = true
backoff.workspace = true
axum.workspace = true
axum-server.workspace = true
bytes.workspace = true
rustls.workspace = true
tower.workspace = true
serde.workspace = true
thiserror = "2.0.3"
axum-macros = "0.4.1"
hyper-util = { version = "0.1.6", features = ["client-legacy"] }
serde_json = "1.0.120"
tower-http = { version = "0.5.2", features = ["trace", "timeout"] }
uuid = { version = "1.10.0", features = ["std", "v7"] }
redis = { version = "0.26.0", features = [
    "tokio-comp",
    "aio",
    "connection-manager",
] }
trait-variant = "0.1.2"
chrono = { version = "0.4", features = ["serde"] }
rcgen = "0.13.1"
parking_lot = "0.12.3"
prometheus-client = "0.22.3"
reqwest = { workspace = true, features = ["rustls-tls", "json"] }
http = "1.2.0"

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
rustls.workspace = true
